version: '2'

services:
  client:
    build: client
    ports:
      - "4200:4200"

  server:
    build: server
    ports:
      - "3000:3000"

  database:
    image: mongo
    ports:
      - "27017:27017"
